#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2155
set -o errexit
set -o nounset
set -o pipefail
[[ -n "${TRACE+x}" ]] && set -o xtrace

readonly _SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly _ROOT_DIR="$(cd -P -- "$(dirname -- "${_SCRIPT_DIR}")" && pwd -P)" # <-- change "${_DIR}" as it depends on your app

echo "[Todo] docker-compose -f $_SCRIPT_DIR/docker-compose.fot-test.yml up"
docker-compose -f "$_SCRIPT_DIR"/docker-compose.fot-test.yml up
